API provides a way to for user to pay for a subscription
CraftAcademy/fake_news_backend pull request #18
Opened 2019-11-05 10:50 UTC by AlexSaxena

[PT-link](https://www.pivotaltracker.com/story/show/169253777)

## PR content
In this PR we are adding a feature where a User can pay for a subscription and be upgraded to the Subscriber role

## This PR contains:
- Stripe gem
-  Stripe-ruby-mock gem
- Payments Controller
- Unit tests
- Upgrade User role to Subscriber role

## What have we learned?
- How to set up Stripe
- How to utilize the Stripe-ruby-mock gem
- Improved understanding of RSpec and related technologies

2019-11-05 11:03 UTC, shsteindorsson approved these changes

2019-11-05 12:58 UTC, lucamarial approved these changes

2019-11-05 12:58 UTC, jonas-masharqa approved these changes

2019-11-05 13:56 UTC, clalil approved these changes

2019-11-05 14:22 UTC, faraznaeem requested changes

2019-11-05 14:22 UTC, faraznaeem commented on app/controllers/payments_controller.rb
> +      amount = 1000
why is the value here hard coded?

2019-11-05 14:22 UTC, faraznaeem commented on app/controllers/payments_controller.rb
> +        description: 'New Fake News Subscriber',
perhaps use the user's name here instead?

2019-11-05 14:22 UTC, faraznaeem commented on config/routes.rb
> +    resources :payments, only: [:index, :create]
where is the `:index` action?

2019-11-05 14:22 UTC, faraznaeem commented on spec/requests/v1/api_provides_a_way_to_add_subscription_spec.rb
> +  describe 'User would like to pay for subscritption' do
typo subscription

2019-11-05 14:22 UTC, faraznaeem commented on spec/requests/v1/api_provides_a_way_to_add_subscription_spec.rb
> +      expect(user.role).to eq('subscriber')
is it good to have multiple `expectations` in the same `it` block?

2019-11-05 14:26 UTC, shsteindorsson commented on app/controllers/payments_controller.rb
> +      amount = 1000
The plan was to save any subscription related things for the user-story where we add the subscription options.

2019-11-05 16:01 UTC, AlexSaxena commented on spec/requests/v1/api_provides_a_way_to_add_subscription_spec.rb
> +      expect(user.role).to eq('subscriber')
Resolved

2019-11-05 16:01 UTC, AlexSaxena commented on spec/requests/v1/api_provides_a_way_to_add_subscription_spec.rb
> +  describe 'User would like to pay for subscritption' do
Resolved

2019-11-05 16:02 UTC, AlexSaxena commented on config/routes.rb
> +    resources :payments, only: [:index, :create]
Resolved

2019-11-05 16:30 UTC, shsteindorsson commented on app/controllers/payments_controller.rb
> +        description: 'New Fake News Subscriber',
When authenticating with `user.name` instead of `user.id`, we receive a Stripe error message:
```
Stripe::InvalidRequestError:
       Must provide source or customer.
```

2019-11-06 18:38 UTC, oliverochman approved these changes

2019-11-07 08:09 UTC, merged