Journalist can write articles longer than 250 characters
CraftAcademy/fake_news_backend pull request #19
Opened 2019-11-05 17:45 UTC by shsteindorsson

[PT-link](https://www.pivotaltracker.com/story/show/169573646)

Journalist can write articles longer than 250 characters
=========================================

## PR content
In this PR we are adding the maximum length of an article's content from 250 to 10.000 characters.

## PR content
- Unit test

2019-11-05 17:47 UTC, clalil approved these changes

2019-11-05 17:48 UTC, AlexSaxena approved these changes

2019-11-06 08:43 UTC, lucamarial approved these changes

2019-11-06 08:59 UTC, jonas-masharqa approved these changes

2019-11-06 15:31 UTC, oliverochman requested changes

2019-11-06 15:31 UTC, oliverochman commented on spec/requests/v1/api_provides_possibility_for_journalist_to_create_article_spec.rb
> +      error_post
please put this line in a before block instead

2019-11-06 15:48 UTC, oliverochman approved these changes

2019-11-06 15:48 UTC, merged