Journalist can categorize Articles depending on topic
CraftAcademy/fake_news_backend pull request #20
Opened 2019-11-05 18:11 UTC by AlexSaxena

[PT-link](https://www.pivotaltracker.com/story/show/169253782)

## PR content
In this PR we are adding a feature where a journalist can choose a category for his/her article

## This PR contains:

## What have we learned?

2019-11-07 09:37 UTC, clalil commented on app/controllers/v1/articles_controller.rb
> +
Are these spaces in the actual file as well or is it just Github magic?

2019-11-07 09:37 UTC, shsteindorsson approved these changes

2019-11-07 09:47 UTC, clalil approved these changes

2019-11-07 18:14 UTC, faraznaeem requested changes

2019-11-07 18:14 UTC, faraznaeem commented on spec/models/category_spec.rb
> +require 'rails_helper'
no test for the association's

2019-11-08 10:06 UTC, lucamarial approved these changes

2019-11-08 10:06 UTC, jonas-masharqa approved these changes

2019-11-08 10:14 UTC, GergKllai1 requested changes

2019-11-08 10:14 UTC, GergKllai1 commented on spec/models/category_spec.rb
> +require 'rails_helper'
Still no tests for assications

2019-11-08 10:14 UTC, GergKllai1 commented on spec/requests/v1/api_provides_possibility_for_journalist_to_create_article_spec.rb
> +  let(:category) {FactoryBot.create(:category)}
You don't need FactoryBot, remove it for consistency

2019-11-08 10:14 UTC, GergKllai1 commented on db/seeds.rb
> +user = User.create(email: 'user@mail.com', encrypted_password: 'password', role: 'user')
it is just password, for consistency change it pls

2019-11-08 10:50 UTC, GergKllai1 approved these changes

2019-11-08 10:50 UTC, merged